/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#424844',
        outline: '#737874',
        'outline-variant': '#c2c8c2',
        primary: '#4d6055',
        'on-primary': '#ffffff',
        'primary-container': '#65796d',
        'primary-fixed': '#d2e8da',
        'primary-fixed-dim': '#b6ccbe',
        'on-primary-fixed': '#0d1f17',
        'on-primary-fixed-variant': '#384b41',
        secondary: '#4e6073',
        'on-secondary': '#ffffff',
        'secondary-container': '#cfe2f8',
        'on-secondary-container': '#536478',
        'secondary-fixed': '#d2e4fb',
        'secondary-fixed-dim': '#b6c8de',
        'on-secondary-fixed': '#0a1d2d',
        'on-secondary-fixed-variant': '#37485b',
        tertiary: '#824f39',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#fbb79c',
        'on-tertiary-fixed': '#341102',
        'on-tertiary-fixed-variant': '#693a26',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f4',
        'on-background': '#1b1c19',
        'surface-variant': '#e4e2dd',
      },
    },
  },
  plugins: [],
};